import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <StoreProvider>
                    <div className="flex min-h-screen w-full">
                        <Sidebar />
                        <main className="flex-1 ms-72">{children}</main>
                    </div>
                </StoreProvider>
            </body>
        </html>
    );
}
